import { Routes } from '@angular/router'
import { LayoutShellComponent } from './design-system/layout-shell.component'
import { authGuard, roleGuard } from './guards/auth.guard'
import { AgendaPageComponent } from './pages/agenda-page.component'
import { AccessRedirectPageComponent } from './pages/access-redirect-page.component'
import { ClassroomPageComponent } from './pages/classroom-page.component'
import { UnimestrePageComponent } from './pages/unimestre-page.component'
import { DashboardPageComponent } from './pages/dashboard-page.component'
import { LoginPageComponent } from './pages/login-page.component'
import { ModulePageComponent } from './pages/module-page.component'
import { VestibularPageComponent } from './pages/vestibular-page.component'

export const appRoutes: Routes = [
  { path: 'login', component: LoginPageComponent, title: 'UniCore | Login' },
  {
    path: 'verificar-email',
    loadComponent: () => import('./pages/verify-email-page.component').then((m) => m.VerifyEmailPageComponent),
    title: 'UniCore | Validação de E-mail',
  },
  {
    path: '',
    component: LayoutShellComponent,
    canActivate: [authGuard],
    canActivateChild: [authGuard],
    children: [
      { path: '', component: AccessRedirectPageComponent, title: 'UniCore | Portal' },
      {
        path: 'administracao/dashboards',
        component: ModulePageComponent,
        canActivate: [roleGuard],
        data: {
          roles: ['admin', 'master'],
          moduleTitle: 'Dashboards Administrativos',
          moduleDescription: 'Dashboards e relatórios do sistema.',
        },
        title: 'UniCore | Dashboards Administrativos',
      },
      {
        path: 'administracao/dashboards/agenda',
        component: DashboardPageComponent,
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Relatório de Agenda',
      },
      {
        path: 'administracao/dashboards/reservas',
        loadComponent: () => import('./pages/reservation-dashboard-page.component').then(m => m.ReservationDashboardPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Relatório de Reservas',
      },
      {
        path: 'administracao/dashboards/territorios',
        loadComponent: () => import('./pages/territory-dashboard-page.component').then(m => m.TerritoryDashboardPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Relatório de Territórios & Leads',
      },
      {
        path: 'desenvolvedor/dashboards',
        component: ModulePageComponent,
        canActivate: [roleGuard],
        data: {
          roles: ['master'],
          module: 'desenvolvedor',
          moduleTitle: 'Dashboards do Desenvolvedor',
          moduleDescription: 'Dashboards e relatórios do sistema.',
        },
        title: 'UniCore | Dashboards',
      },
      {
        path: 'desenvolvedor/dashboards/agenda',
        component: DashboardPageComponent,
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Relatório de Agenda',
      },
      {
        path: 'desenvolvedor/dashboards/reservas',
        loadComponent: () => import('./pages/reservation-dashboard-page.component').then(m => m.ReservationDashboardPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Relatório de Reservas',
      },
      {
        path: 'desenvolvedor/dashboards/territorios',
        loadComponent: () => import('./pages/territory-dashboard-page.component').then(m => m.TerritoryDashboardPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Relatório de Territórios & Leads',
      },
      { path: 'agenda', component: AgendaPageComponent, title: 'UniCore | Agenda' },
      
      { path: 'vestibular/agenda', component: AgendaPageComponent, canActivate: [roleGuard], title: 'UniCore | Agenda' },
      { path: 'tesouraria/agenda', component: AgendaPageComponent, canActivate: [roleGuard], title: 'UniCore | Agenda' },
      { path: 'secretaria/agenda', component: AgendaPageComponent, canActivate: [roleGuard], title: 'UniCore | Agenda' },
      { path: 'coordenacao/agenda', component: AgendaPageComponent, canActivate: [roleGuard], title: 'UniCore | Agenda' },
      { path: 'registro-academico/agenda', component: AgendaPageComponent, canActivate: [roleGuard], title: 'UniCore | Agenda' },
      { path: 'administracao/agenda', component: AgendaPageComponent, canActivate: [roleGuard], title: 'UniCore | Agenda' },
      { path: 'desenvolvedor/agenda', component: AgendaPageComponent, canActivate: [roleGuard], title: 'UniCore | Agenda' },
      { path: 'professor/agenda', component: AgendaPageComponent, canActivate: [roleGuard], title: 'UniCore | Agenda' },
      { path: 'aluno/agenda', component: AgendaPageComponent, canActivate: [roleGuard], title: 'UniCore | Agenda' },
      {
        path: 'vestibular',
        component: ModulePageComponent,
        canActivate: [roleGuard],
        data: {
          roles: ['vestibular', 'admin', 'master'],
          moduleTitle: 'Vestibular',
          moduleDescription: 'Central de correção de avaliações e gerência do processo seletivo.',
        },
        title: 'UniCore | Vestibular',
      },
      {
        path: 'vestibular/corrigir',
        component: VestibularPageComponent,
        canActivate: [roleGuard],
        data: { roles: ['vestibular', 'admin', 'master'] },
        title: 'UniCore | Corrigir Avaliação',
      },
      {
        path: 'vestibular/cadastros',
        component: ModulePageComponent,
        canActivate: [roleGuard],
        data: {
          roles: ['vestibular', 'admin', 'master'],
          module: 'vestibular',
          moduleTitle: 'Cadastros',
          moduleDescription: 'Gerenciamento de cadastros territoriais e leads do vestibular.',
        },
        title: 'UniCore | Cadastros',
      },
      {
        path: 'vestibular/cadastros/territorios',
        loadComponent: () => import('./pages/territory-management-page.component').then(m => m.TerritoryManagementPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['vestibular', 'admin', 'master'] },
        title: 'UniCore | Cadastro de Territórios',
      },
      {
        path: 'vestibular/cadastros/leads',
        loadComponent: () => import('./pages/leads-page.component').then(m => m.LeadsPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['vestibular', 'admin', 'master'] },
        title: 'UniCore | Gestão de Leads',
      },
      {
        path: 'vestibular/cadastros/mapa',
        loadComponent: () => import('./pages/territory-map-page.component').then(m => m.TerritoryMapPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['vestibular', 'admin', 'master'] },
        title: 'UniCore | Mapa Territorial & Semáforo',
      },
      {
        path: 'vestibular/dashboards/territorios',
        loadComponent: () => import('./pages/territory-dashboard-page.component').then(m => m.TerritoryDashboardPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['vestibular', 'admin', 'master'] },
        title: 'UniCore | Relatório de Territórios & Leads',
      },
      ...[
        ['tesouraria', 'tesouraria', 'Tesouraria', ['tesouraria', 'admin', 'master']],
        ['secretaria', 'secretaria', 'Secretaria', ['secretaria', 'admin', 'master']],
        ['coordenacao', 'coordenacao', 'Coordenação', ['coordenacao', 'admin', 'master']],
        ['registro-academico', 'registro_academico', 'Registro Acadêmico', ['registro_academico', 'admin', 'master']],
        ['professor', 'professor', 'Professor', ['professor', 'admin', 'master', 'coordenacao']],
        ['aluno', 'aluno', 'Aluno', ['aluno', 'admin', 'master', 'vestibular', 'tesouraria', 'secretaria', 'coordenacao', 'registro_academico', 'professor']],
      ].map(([path, module, moduleTitle, roles]) => ({
        path: path as string,
        component: ModulePageComponent,
        canActivate: [roleGuard],
        data: {
          roles,
          module,
          moduleTitle,
          moduleDescription: `Área de ${moduleTitle}, preparada para os fluxos do backend.`,
        },
        title: `UniCore | ${moduleTitle}`,
      })),
      {
        path: 'coordenacao/unimestre',
        component: UnimestrePageComponent,
        canActivate: [roleGuard],
        data: { roles: ['coordenacao', 'admin', 'master'] },
        title: 'UniCore | Coordenação - Cursos e Turmas',
      },
      {
        path: 'coordenacao/classroom',
        component: ClassroomPageComponent,
        canActivate: [roleGuard],
        data: { roles: ['coordenacao', 'admin', 'master'] },
        title: 'UniCore | Google Classroom',
      },
      {
        path: 'administracao',
        component: ModulePageComponent,
        canActivate: [roleGuard],
        data: {
          roles: ['admin', 'master'],
          moduleTitle: 'Administração',
          moduleDescription: 'Gerenciamento de integrações, relatórios em lote e recursos globais.',
        },
        title: 'UniCore | Administração',
      },
      {
        path: 'administracao/unimestre',
        component: UnimestrePageComponent,
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Integração Unimestre',
      },
      {
        path: 'administracao/classroom',
        component: ClassroomPageComponent,
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Google Classroom',
      },
      {
        path: 'administracao/corrigir',
        component: VestibularPageComponent,
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Corrigir Avaliação',
      },
      {
        path: 'administracao/cadastros',
        component: ModulePageComponent,
        canActivate: [roleGuard],
        data: {
          roles: ['admin', 'master'],
          module: 'administracao',
          moduleTitle: 'Cadastros',
          moduleDescription: 'Gerenciamento de cadastros de usuários e itens de reserva.',
        },
        title: 'UniCore | Cadastros',
      },
      {
        path: 'desenvolvedor',
        component: ModulePageComponent,
        canActivate: [roleGuard],
        data: {
          roles: ['master'],
          module: 'desenvolvedor',
          moduleTitle: 'Configurações do desenvolvedor',
          moduleDescription: 'Área exclusiva do usuário master para configurações técnicas e de código.',
        },
        title: 'UniCore | Desenvolvedor',
      },
      {
        path: 'desenvolvedor/unimestre',
        component: UnimestrePageComponent,
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Integração Unimestre',
      },
      {
        path: 'desenvolvedor/classroom',
        component: ClassroomPageComponent,
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Google Classroom',
      },
      {
        path: 'desenvolvedor/corrigir',
        component: VestibularPageComponent,
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Corrigir Avaliação',
      },
      {
        path: 'desenvolvedor/cadastros',
        component: ModulePageComponent,
        canActivate: [roleGuard],
        data: {
          roles: ['master'],
          module: 'desenvolvedor',
          moduleTitle: 'Cadastros',
          moduleDescription: 'Gerenciamento de cadastros de usuários e itens de reserva.',
        },
        title: 'UniCore | Cadastros',
      },
      {
        path: 'administracao/cadastros/usuarios',
        loadComponent: () => import('./pages/user-registration-page.component').then(m => m.UserRegistrationPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Cadastro de Usuário',
      },
      {
        path: 'administracao/cadastros/itens-reserva',
        loadComponent: () => import('./pages/item-registration-page.component').then(m => m.ItemRegistrationPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Cadastro de Itens de Reserva',
      },
      {
        path: 'administracao/cadastros/itens',
        redirectTo: 'administracao/cadastros/itens-reserva',
        pathMatch: 'full',
      },
      {
        path: 'administracao/cadastros/eventos',
        loadComponent: () => import('./pages/event-registration-page.component').then(m => m.EventRegistrationPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Eventos para Certificados',
      },
      {
        path: 'administracao/cadastros/territorios',
        loadComponent: () => import('./pages/territory-management-page.component').then(m => m.TerritoryManagementPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Cadastro de Territórios',
      },
      {
        path: 'administracao/cadastros/leads',
        loadComponent: () => import('./pages/leads-page.component').then(m => m.LeadsPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Gestão de Leads',
      },
      {
        path: 'administracao/cadastros/mapa',
        loadComponent: () => import('./pages/territory-map-page.component').then(m => m.TerritoryMapPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Mapa Territorial & Semáforo',
      },
      {
        path: 'desenvolvedor/cadastros/usuarios',
        loadComponent: () => import('./pages/user-registration-page.component').then(m => m.UserRegistrationPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Cadastro de Usuário',
      },
      {
        path: 'desenvolvedor/cadastros/itens-reserva',
        loadComponent: () => import('./pages/item-registration-page.component').then(m => m.ItemRegistrationPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Cadastro de Itens de Reserva',
      },
      {
        path: 'desenvolvedor/cadastros/itens',
        redirectTo: 'desenvolvedor/cadastros/itens-reserva',
        pathMatch: 'full',
      },
      {
        path: 'desenvolvedor/cadastros/eventos',
        loadComponent: () => import('./pages/event-registration-page.component').then(m => m.EventRegistrationPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Eventos para Certificados',
      },
      {
        path: 'desenvolvedor/cadastros/territorios',
        loadComponent: () => import('./pages/territory-management-page.component').then(m => m.TerritoryManagementPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Cadastro de Territórios',
      },
      {
        path: 'desenvolvedor/cadastros/leads',
        loadComponent: () => import('./pages/leads-page.component').then(m => m.LeadsPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Gestão de Leads',
      },
      {
        path: 'desenvolvedor/cadastros/mapa',
        loadComponent: () => import('./pages/territory-map-page.component').then(m => m.TerritoryMapPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Mapa Territorial & Semáforo',
      },
      {
        path: 'aluno/eventos',
        loadComponent: () => import('./pages/event-catalog-page.component').then(m => m.EventCatalogPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['aluno', 'admin', 'master'] },
        title: 'UniCore | Eventos e Certificados',
      },
      {
        path: 'professor/eventos',
        loadComponent: () => import('./pages/event-catalog-page.component').then(m => m.EventCatalogPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['professor', 'admin', 'master'] },
        title: 'UniCore | Eventos e Certificados',
      },
      {
        path: 'coordenacao/eventos',
        loadComponent: () => import('./pages/event-catalog-page.component').then(m => m.EventCatalogPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['coordenacao', 'admin', 'master'] },
        title: 'UniCore | Eventos e Certificados',
      },
      {
        path: 'administracao/eventos',
        loadComponent: () => import('./pages/event-catalog-page.component').then(m => m.EventCatalogPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Eventos Acadêmicos',
      },
      {
        path: 'desenvolvedor/eventos',
        loadComponent: () => import('./pages/event-catalog-page.component').then(m => m.EventCatalogPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Eventos Acadêmicos',
      },
      {
        path: 'eventos',
        loadComponent: () => import('./pages/event-catalog-page.component').then(m => m.EventCatalogPageComponent),
        title: 'UniCore | Eventos e Certificados',
      },
      {
        path: 'administracao/reservas',
        loadComponent: () => import('./pages/item-reservation-page.component').then(m => m.ItemReservationPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Reserva de Itens',
      },
      {
        path: 'administracao/reserva',
        redirectTo: 'administracao/reservas',
        pathMatch: 'full',
      },
      {
        path: 'desenvolvedor/reservas',
        loadComponent: () => import('./pages/item-reservation-page.component').then(m => m.ItemReservationPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Reserva de Itens',
      },
      {
        path: 'desenvolvedor/reserva',
        redirectTo: 'desenvolvedor/reservas',
        pathMatch: 'full',
      },
      {
        path: 'administracao/certificados',
        loadComponent: () => import('./pages/certificates-page.component').then(m => m.CertificatesPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Gestão de Certificados',
      },
      {
        path: 'desenvolvedor/certificados',
        loadComponent: () => import('./pages/certificates-page.component').then(m => m.CertificatesPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Gestão de Certificados',
      },
      {
        path: 'professor/reservas',
        loadComponent: () => import('./pages/item-reservation-page.component').then(m => m.ItemReservationPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['professor', 'admin', 'master'] },
        title: 'UniCore | Reserva de Itens',
      },
      {
        path: 'professor/reserva',
        redirectTo: 'professor/reservas',
        pathMatch: 'full',
      },
      {
        path: 'aluno/salas',
        loadComponent: () => import('./pages/student-rooms-page.component').then(m => m.StudentRoomsPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['aluno', 'admin', 'master', 'professor', 'coordenacao'] },
        title: 'UniCore | Salas e Laboratórios',
      },
      {
        path: 'administracao/salas',
        loadComponent: () => import('./pages/student-rooms-page.component').then(m => m.StudentRoomsPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['admin', 'master'] },
        title: 'UniCore | Salas e Laboratórios',
      },
      {
        path: 'desenvolvedor/salas',
        loadComponent: () => import('./pages/student-rooms-page.component').then(m => m.StudentRoomsPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['master'] },
        title: 'UniCore | Salas e Laboratórios',
      },
      {
        path: 'professor/salas',
        loadComponent: () => import('./pages/student-rooms-page.component').then(m => m.StudentRoomsPageComponent),
        canActivate: [roleGuard],
        data: { roles: ['professor', 'admin', 'master'] },
        title: 'UniCore | Salas e Laboratórios',
      },
      {
        path: 'alterar-senha',
        loadComponent: () => import('./pages/change-password-page.component').then(m => m.ChangePasswordPageComponent),
        title: 'UniCore | Alteração de Senha',
      },
      {
        path: 'vestibular/alterar-senha',
        loadComponent: () => import('./pages/change-password-page.component').then(m => m.ChangePasswordPageComponent),
        canActivate: [roleGuard],
        title: 'UniCore | Alteração de Senha',
      },
      {
        path: 'tesouraria/alterar-senha',
        loadComponent: () => import('./pages/change-password-page.component').then(m => m.ChangePasswordPageComponent),
        canActivate: [roleGuard],
        title: 'UniCore | Alteração de Senha',
      },
      {
        path: 'secretaria/alterar-senha',
        loadComponent: () => import('./pages/change-password-page.component').then(m => m.ChangePasswordPageComponent),
        canActivate: [roleGuard],
        title: 'UniCore | Alteração de Senha',
      },
      {
        path: 'coordenacao/alterar-senha',
        loadComponent: () => import('./pages/change-password-page.component').then(m => m.ChangePasswordPageComponent),
        canActivate: [roleGuard],
        title: 'UniCore | Alteração de Senha',
      },
      {
        path: 'registro-academico/alterar-senha',
        loadComponent: () => import('./pages/change-password-page.component').then(m => m.ChangePasswordPageComponent),
        canActivate: [roleGuard],
        title: 'UniCore | Alteração de Senha',
      },
      {
        path: 'professor/alterar-senha',
        loadComponent: () => import('./pages/change-password-page.component').then(m => m.ChangePasswordPageComponent),
        canActivate: [roleGuard],
        title: 'UniCore | Alteração de Senha',
      },
      {
        path: 'aluno/alterar-senha',
        loadComponent: () => import('./pages/change-password-page.component').then(m => m.ChangePasswordPageComponent),
        canActivate: [roleGuard],
        title: 'UniCore | Alteração de Senha',
      },
      {
        path: 'administracao/alterar-senha',
        loadComponent: () => import('./pages/change-password-page.component').then(m => m.ChangePasswordPageComponent),
        canActivate: [roleGuard],
        title: 'UniCore | Alteração de Senha',
      },
      {
        path: 'desenvolvedor/alterar-senha',
        loadComponent: () => import('./pages/change-password-page.component').then(m => m.ChangePasswordPageComponent),
        canActivate: [roleGuard],
        title: 'UniCore | Alteração de Senha',
      }
    ],
  },
  { path: '**', redirectTo: '' },
]
